server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    location / {
				return 200 "<h1>Hi!</h1><p>Welcome to default Nginx proxy page.</p><p>You are seeing this page because you have not set up any domains.</p>";
				add_header Content-Type text/html;
		}
}